# Generated by Django 5.1.4 on 2024-12-26 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the form', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Description of the form (Optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the form was created')),
                ('admin', models.ForeignKey(help_text='Admin of the form', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], help_text='Type of question', max_length=20)),
                ('text', models.TextField(help_text='Text of the question')),
                ('order', models.PositiveIntegerField(help_text='Order of the question in the form')),
                ('options', models.JSONField(blank=True, help_text='Options for dropdown or checkbox questions', null=True)),
                ('form', models.ForeignKey(help_text='Question for the form', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the response was submitted')),
                ('form', models.ForeignKey(help_text='Form for which the response is', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='Text answer for the question', null=True)),
                ('selected_options', models.JSONField(blank=True, help_text='Selected options for dropdown or checkbox questions', null=True)),
                ('question', models.ForeignKey(help_text='Question for which the answer is', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.question')),
                ('response', models.ForeignKey(help_text='Response for which the answer is', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.response')),
            ],
        ),
    ]
